// inspect.js - GENERATED by gateway_config.py (ADR 0015 sec 3). DO NOT hand-edit.
// Response-body capture for surfaces at inspect level `request+response`. Only imported
// when nginx.conf.template carries `js_import` (i.e. some surface needs it); otherwise this
// file sits mounted-but-unused. See gateway_config.py render_njs_* for the wiring.

// Cap accumulated bytes so a large model response can't balloon worker memory. Beyond the
// cap the body is truncated with a marker (the blue-team still sees the head + that it ran over).
var MAX_BYTES = 262144;  // 256 KiB

// js_body_filter: called per response chunk. Accumulate onto the request object, then
// forward the chunk UNCHANGED downstream via r.sendBuffer (the filter must forward or the
// response is withheld).
function filter(r, data, flags) {
    if (r.variables.insp_capping !== '1') {
        var cur = r.buf_resp || '';
        if (cur.length < MAX_BYTES) {
            r.buf_resp = cur + data;
            if (r.buf_resp.length >= MAX_BYTES) {
                r.buf_resp = r.buf_resp.substring(0, MAX_BYTES) + '...[truncated]';
            }
        }
    }
    r.sendBuffer(data, flags);
}

// js_set target: return the accumulated body at log time.
function respBody(r) {
    return r.buf_resp || '';
}

export default { filter, respBody };
